//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJC_Foodproject.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJC_Foodproject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aliooilo {
            get {
                object obj = ResourceManager.GetObject("aliooilo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap armysoup {
            get {
                object obj = ResourceManager.GetObject("armysoup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap beannoodle {
            get {
                object obj = ResourceManager.GetObject("beannoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibimbob {
            get {
                object obj = ResourceManager.GetObject("bibimbob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibimnoodle {
            get {
                object obj = ResourceManager.GetObject("bibimnoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bonehangover {
            get {
                object obj = ResourceManager.GetObject("bonehangover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bread {
            get {
                object obj = ResourceManager.GetObject("bread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap buffalowings {
            get {
                object obj = ResourceManager.GetObject("buffalowings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bulgogi {
            get {
                object obj = ResourceManager.GetObject("bulgogi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap creampasta {
            get {
                object obj = ResourceManager.GetObject("creampasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap curryrice {
            get {
                object obj = ResourceManager.GetObject("curryrice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap donkatsu {
            get {
                object obj = ResourceManager.GetObject("donkatsu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap eelrice {
            get {
                object obj = ResourceManager.GetObject("eelrice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap friedchicken {
            get {
                object obj = ResourceManager.GetObject("friedchicken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap friedrice {
            get {
                object obj = ResourceManager.GetObject("friedrice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ganjjazang {
            get {
                object obj = ResourceManager.GetObject("ganjjazang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gookbob {
            get {
                object obj = ResourceManager.GetObject("gookbob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hamberger {
            get {
                object obj = ResourceManager.GetObject("hamberger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iceage {
            get {
                object obj = ResourceManager.GetObject("iceage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap inkpasta {
            get {
                object obj = ResourceManager.GetObject("inkpasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap isaac {
            get {
                object obj = ResourceManager.GetObject("isaac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jabtangbob {
            get {
                object obj = ResourceManager.GetObject("jabtangbob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jaengbanjjazang {
            get {
                object obj = ResourceManager.GetObject("jaengbanjjazang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jaeyook {
            get {
                object obj = ResourceManager.GetObject("jaeyook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janchinoodle {
            get {
                object obj = ResourceManager.GetObject("janchinoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap japchaebob {
            get {
                object obj = ResourceManager.GetObject("japchaebob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jjambbong {
            get {
                object obj = ResourceManager.GetObject("jjambbong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jjambbongbob {
            get {
                object obj = ResourceManager.GetObject("jjambbongbob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jjazang {
            get {
                object obj = ResourceManager.GetObject("jjazang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jjazangbob {
            get {
                object obj = ResourceManager.GetObject("jjazangbob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap katsudon {
            get {
                object obj = ResourceManager.GetObject("katsudon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap kebob {
            get {
                object obj = ResourceManager.GetObject("kebob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap knifenoodle {
            get {
                object obj = ResourceManager.GetObject("knifenoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap kyudong {
            get {
                object obj = ResourceManager.GetObject("kyudong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap lasagna {
            get {
                object obj = ResourceManager.GetObject("lasagna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap majesoba {
            get {
                object obj = ResourceManager.GetObject("majesoba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap maknoodle {
            get {
                object obj = ResourceManager.GetObject("maknoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap mapatofu {
            get {
                object obj = ResourceManager.GetObject("mapatofu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap meatjjambbong {
            get {
                object obj = ResourceManager.GetObject("meatjjambbong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pizza {
            get {
                object obj = ResourceManager.GetObject("pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ramen {
            get {
                object obj = ResourceManager.GetObject("ramen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ramyun {
            get {
                object obj = ResourceManager.GetObject("ramyun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rosepasta {
            get {
                object obj = ResourceManager.GetObject("rosepasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap sakedon {
            get {
                object obj = ResourceManager.GetObject("sakedon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap sandwich {
            get {
                object obj = ResourceManager.GetObject("sandwich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap seafoodpasta {
            get {
                object obj = ResourceManager.GetObject("seafoodpasta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap shrimpfriedrice {
            get {
                object obj = ResourceManager.GetObject("shrimpfriedrice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap soba {
            get {
                object obj = ResourceManager.GetObject("soba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap softtofu {
            get {
                object obj = ResourceManager.GetObject("softtofu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap steak {
            get {
                object obj = ResourceManager.GetObject("steak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap sushi {
            get {
                object obj = ResourceManager.GetObject("sushi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tomatoe {
            get {
                object obj = ResourceManager.GetObject("tomatoe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap udon {
            get {
                object obj = ResourceManager.GetObject("udon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap yakisoba {
            get {
                object obj = ResourceManager.GetObject("yakisoba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   가츠동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 가츠동 {
            get {
                return ResourceManager.GetString("가츠동", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간짜장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 간짜장 {
            get {
                return ResourceManager.GetString("간짜장", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계란볶음밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 계란볶음밥 {
            get {
                return ResourceManager.GetString("계란볶음밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   국밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 국밥 {
            get {
                return ResourceManager.GetString("국밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   규동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 규동 {
            get {
                return ResourceManager.GetString("규동", resourceCulture);
            }
        }
        
        /// <summary>
        ///   냉면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 냉면 {
            get {
                return ResourceManager.GetString("냉면", resourceCulture);
            }
        }
        
        /// <summary>
        ///   돈까스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 돈까스 {
            get {
                return ResourceManager.GetString("돈까스", resourceCulture);
            }
        }
        
        /// <summary>
        ///   돌솥비빔밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 돌솥비빔밥 {
            get {
                return ResourceManager.GetString("돌솥비빔밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라멘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 라멘 {
            get {
                return ResourceManager.GetString("라멘", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 라면 {
            get {
                return ResourceManager.GetString("라면", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라자냐과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 라자냐 {
            get {
                return ResourceManager.GetString("라자냐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로제파스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 로제파스타 {
            get {
                return ResourceManager.GetString("로제파스타", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마제소바과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 마제소바 {
            get {
                return ResourceManager.GetString("마제소바", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마파두부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 마파두부 {
            get {
                return ResourceManager.GetString("마파두부", resourceCulture);
            }
        }
        
        /// <summary>
        ///   막국수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 막국수 {
            get {
                return ResourceManager.GetString("막국수", resourceCulture);
            }
        }
        
        /// <summary>
        ///   먹물파스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 먹물파스타 {
            get {
                return ResourceManager.GetString("먹물파스타", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메밀소바과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 메밀소바 {
            get {
                return ResourceManager.GetString("메밀소바", resourceCulture);
            }
        }
        
        /// <summary>
        ///   버팔로윙과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 버팔로윙 {
            get {
                return ResourceManager.GetString("버팔로윙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부대찌개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 부대찌개 {
            get {
                return ResourceManager.GetString("부대찌개", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불고기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 불고기 {
            get {
                return ResourceManager.GetString("불고기", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비빔국수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 비빔국수 {
            get {
                return ResourceManager.GetString("비빔국수", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빵과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 빵 {
            get {
                return ResourceManager.GetString("빵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   뼈해장국과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 뼈해장국 {
            get {
                return ResourceManager.GetString("뼈해장국", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새우볶음밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 새우볶음밥 {
            get {
                return ResourceManager.GetString("새우볶음밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   샌드위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 샌드위치 {
            get {
                return ResourceManager.GetString("샌드위치", resourceCulture);
            }
        }
        
        /// <summary>
        ///   순두부찌개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 순두부찌개 {
            get {
                return ResourceManager.GetString("순두부찌개", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스테이크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 스테이크 {
            get {
                return ResourceManager.GetString("스테이크", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알리오 올리오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 알리오_올리오 {
            get {
                return ResourceManager.GetString("알리오 올리오", resourceCulture);
            }
        }
        
        /// <summary>
        ///   야키소바과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 야키소바 {
            get {
                return ResourceManager.GetString("야키소바", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연어덮밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 연어덮밥 {
            get {
                return ResourceManager.GetString("연어덮밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 우동 {
            get {
                return ResourceManager.GetString("우동", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잔치국수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 잔치국수 {
            get {
                return ResourceManager.GetString("잔치국수", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잡채밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 잡채밥 {
            get {
                return ResourceManager.GetString("잡채밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잡탕밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 잡탕밥 {
            get {
                return ResourceManager.GetString("잡탕밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장어덮밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 장어덮밥 {
            get {
                return ResourceManager.GetString("장어덮밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쟁반짜장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 쟁반짜장 {
            get {
                return ResourceManager.GetString("쟁반짜장", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제육볶음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 제육볶음 {
            get {
                return ResourceManager.GetString("제육볶음", resourceCulture);
            }
        }
        
        /// <summary>
        ///   짜장면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 짜장면 {
            get {
                return ResourceManager.GetString("짜장면", resourceCulture);
            }
        }
        
        /// <summary>
        ///   짜장밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 짜장밥 {
            get {
                return ResourceManager.GetString("짜장밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   짬뽕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 짬뽕 {
            get {
                return ResourceManager.GetString("짬뽕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   짬뽕밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 짬뽕밥 {
            get {
                return ResourceManager.GetString("짬뽕밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차돌짬뽕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 차돌짬뽕 {
            get {
                return ResourceManager.GetString("차돌짬뽕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 초밥 {
            get {
                return ResourceManager.GetString("초밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   치킨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 치킨 {
            get {
                return ResourceManager.GetString("치킨", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카레라이스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 카레라이스 {
            get {
                return ResourceManager.GetString("카레라이스", resourceCulture);
            }
        }
        
        /// <summary>
        ///   칼국수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 칼국수 {
            get {
                return ResourceManager.GetString("칼국수", resourceCulture);
            }
        }
        
        /// <summary>
        ///   케밥과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 케밥 {
            get {
                return ResourceManager.GetString("케밥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콩국수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 콩국수 {
            get {
                return ResourceManager.GetString("콩국수", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크림파스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 크림파스타 {
            get {
                return ResourceManager.GetString("크림파스타", resourceCulture);
            }
        }
        
        /// <summary>
        ///   토마토스파게티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 토마토스파게티 {
            get {
                return ResourceManager.GetString("토마토스파게티", resourceCulture);
            }
        }
        
        /// <summary>
        ///   토스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 토스트 {
            get {
                return ResourceManager.GetString("토스트", resourceCulture);
            }
        }
        
        /// <summary>
        ///   피자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 피자 {
            get {
                return ResourceManager.GetString("피자", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해물파스타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 해물파스타 {
            get {
                return ResourceManager.GetString("해물파스타", resourceCulture);
            }
        }
        
        /// <summary>
        ///   햄버거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 햄버거 {
            get {
                return ResourceManager.GetString("햄버거", resourceCulture);
            }
        }
    }
}
